name: CD

on:
  push:
    branches:
      - main
    paths:
      - "supabase/migrations/**"
      - "supabase/config.toml"
      - "supabase/templates/**"
  workflow_dispatch:

jobs:
  deploy-prod-db:
    name: Deploy Production Database
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.115.0

      - name: Link to Production Project
        run: supabase link --project-ref ${{ vars.SUPABASE_PROD_PROJECT_ID }}

      - name: Dry-run migrations
        run: supabase db push --dry-run

      - name: Push migrations to Production DB
        run: supabase db push

      - name: Push config to Production Project
        run: supabase config push
